name: Auto Categorize Markdown
on:
  push:
    paths:
      - "uploads/*.md"
    branches:
      - "main"
  pull_request:
    types:
      - closed
    branches:
      - "main"
  workflow_dispatch:



jobs:
  categorize:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Smart Composer
        uses: FacerAin/smart-composer@v0.1.8
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          categories: "Python,Java,Network,Algorithm,Cloud,Database,Machine Learning,Design Pattern,Etc"
          uploads_pattern: "uploads/*.md"
          docs_dir: "docs"
          rewrite: true
          update-readme: true
          
      - name: Commit changes without new commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # 최신 커밋을 확인하고 변경 사항이 있는지 체크
          if ! git diff --quiet; then
            git add .

            # 최신 커밋을 수정 (commit ID 유지)
            git commit --amend --no-edit

            # 최신 커밋을 강제로 push (기존 커밋 덮어쓰기)
            git push --force
          else
            echo "No changes detected, skipping commit."
          fi

